---
- name: Deploy a web app on multiple servers
  hosts: all
  become: yes

  tasks:
  - name: update package managers
    yum:
      name: '*'
      state: latest
    when: ansible_pkg_mgr == "dnf"
  
  - name: update package managers
    apt:
      name: '*'
      state: latest
    when: ansible_pkg_mgr == "apt"
...