---
- name: Deploy a web app on multiple servers
  hosts: all
  become: yes

  tasks:
  - name: update package managers
    yum:
      name: '*'
      state: latest
    when: ansible_pkg_mgr == "dnf"
  
  - name: Update all packages (Debian/Ubuntu)
    apt:
      update_cache: yes
      upgrade: full
      state: latest
    when: ansible_pkg_mgr == "apt"

  - name: install httpd
    yum:
    name: httpd
    state: present
    when: ansible_pkg_mgr == "apt"

  - name: install httpd
    apt:
    name: apache2
    state: present
    when: ansible_pkg_mgr == "apt"

...