---
  # tasks file for ecomm
- name: restart httpd
  service:
    name: httpd
    state: restarted
    enabled: yes
  when: ansible_pkg_mgr == 'dnf'

- name: restart apache2
  service:
    name: apache2
    state: restarted
    enabled: yes
  when: ansible_pkg_mgr == 'apt'
...