---
  # tasks file for ecomm
  - name: restart httpd
    service:
    name: httpd
    state: restarted
    when: ansible_pkg_mgr == 'dnf'

  - name: restart apache2
    service:
      name: apache2
      state: restarted
    when: ansible_pkg_mgr == 'apt'
...