---
- name: Deploy a web app on multiple servers
  hosts: all
  become: yes

  tasks:
  - name: update package managers
    yum:
      name: '*'
      state: latest
    when: ansible_pkg_mgr == "dnf"
  
  - name: Update all packages (Debian/Ubuntu)
    apt:
      update_cache: yes
      upgrade: full
      state: latest
    when: ansible_pkg_mgr == "apt"

  - name: install git
    yum:
     name: git
     state: present
    when: ansible_pkg_mgr == "dnf"

  - name: install git
    apt:
     name: git
     state: present
    when: ansible_pkg_mgr == "apt"

  - name: install httpd
    yum:
     name: httpd
     state: present
    when: ansible_pkg_mgr == "dnf"

  - name: install httpd apache2
    apt:
     name: apache2
     state: present
    when: ansible_pkg_mgr == "apt"

  - name: start httpd
    service:
      name: httpd
      state: started 
      enabled: yes
    when: ansible_pkg_mgr == "dnf"

  - name: start httpd
    service:
      name: apache2
      state: started 
      enabled: yes
    when: ansible_pkg_mgr == "apt"
  
  - name: copy html files
    git:
      repo: https://github.com/BasedOnBelieve/ecomm-3.git
      dest: /var/www/html
    when: ansible_pkg_mgr == "apt" or ansible_pkg_mgr == "dnf"

...