---
- name: copy a static webpage to nodes using template module
  hosts: all
  become: yes

  tasks:
    - name: update webpage
      template:
        src: dynamic.j2
        dest: /var/www/html/dynamic.html
...