---
- name: copy a dynamically using template module
  hosts: all
  become: yes
  vars: 
    host_user: believe mene

  tasks:
    - name: update webpage
      template:
        src: dynamic.j2
        dest: /var/www/html/dynamic.html
...